"""Public Belief State (PBS) for 6-max NLH poker.

A PBS represents, for each player, a probability distribution over the 1326
possible 2-card starting hands, conditioned on:
  - The public board cards seen so far.
  - The public action history (bets, raises, calls, folds).

The PBS is the central data structure for the TurboReBeL algorithm:
  1. A PBS is sampled or generated by traversing a game trajectory.
  2. A depth-limited subgame is solved starting from the PBS.
  3. The resulting values are used to train the value network.

References:
  Brown et al., "TurboReBeL: 250× Accelerated Belief Learning for large
  Imperfect-Information Extensive-Form Games", 2021.
"""

from __future__ import annotations

from typing import Dict, List, Optional

import numpy as np

from ..game.card import NUM_CARDS, NUM_HANDS, hand_index, index_to_hand
from ..game.state import GameState, Street, NUM_PLAYERS

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _uniform_range(board: List[int]) -> np.ndarray:
    """Return a uniform hand range over all holdings not blocked by *board*.

    The returned array has shape (NUM_HANDS,) and sums to 1.
    """
    board_set = set(board)
    weights = np.zeros(NUM_HANDS, dtype=float)
    for idx in range(NUM_HANDS):
        c1, c2 = index_to_hand(idx)
        if c1 not in board_set and c2 not in board_set:
            weights[idx] = 1.0
    total = weights.sum()
    if total > 0:
        weights /= total
    return weights


# ---------------------------------------------------------------------------
# PublicBeliefState
# ---------------------------------------------------------------------------


class PublicBeliefState:
    """Probability distribution over private hand-profiles given public info.

    Attributes:
        ranges: Array of shape (num_players, NUM_HANDS) where
            ``ranges[p, h]`` is the probability that player *p* holds hand *h*.
        board: Community cards currently visible.
        pot: Total pot size (chips).
        stacks: Array of per-player stack sizes.
        bets: Array of per-player current-street bets.
        street: Current betting round.
        folded: Boolean array indicating which players have folded.
        action_history_str: Compact string encoding of the action history,
            used for hashing / serialisation.
    """

    def __init__(
        self,
        ranges: np.ndarray,
        board: List[int],
        pot: float,
        stacks: np.ndarray,
        bets: np.ndarray,
        street: Street,
        folded: np.ndarray,
        action_history_str: str = "",
    ) -> None:
        assert ranges.shape == (NUM_PLAYERS, NUM_HANDS), (
            f"ranges must be ({NUM_PLAYERS}, {NUM_HANDS}), got {ranges.shape}"
        )
        self.ranges: np.ndarray = ranges.copy()
        self.board: List[int] = list(board)
        self.pot: float = float(pot)
        self.stacks: np.ndarray = stacks.copy()
        self.bets: np.ndarray = bets.copy()
        self.street: Street = street
        self.folded: np.ndarray = folded.copy()
        self.action_history_str: str = action_history_str

    # ------------------------------------------------------------------
    # Factory methods
    # ------------------------------------------------------------------

    @classmethod
    def initial(cls, board: Optional[List[int]] = None) -> "PublicBeliefState":
        """Create a PBS with uniform ranges for all players."""
        board = board or []
        ranges = np.stack([_uniform_range(board)] * NUM_PLAYERS, axis=0)
        stacks = np.zeros(NUM_PLAYERS, dtype=float)
        bets = np.zeros(NUM_PLAYERS, dtype=float)
        folded = np.zeros(NUM_PLAYERS, dtype=bool)
        return cls(
            ranges=ranges,
            board=board,
            pot=0.0,
            stacks=stacks,
            bets=bets,
            street=Street.PREFLOP,
            folded=folded,
        )

    @classmethod
    def from_game_state(cls, state: GameState) -> "PublicBeliefState":
        """Construct a PBS from a GameState with known hole cards (for training).

        In a real game the ranges would be maintained by Bayesian updating;
        here we initialise to uniform (minus blockers) for all players without
        known hole cards, and to the true hand for players whose cards are set.
        """
        board = list(state.board)
        ranges = np.zeros((NUM_PLAYERS, NUM_HANDS), dtype=float)
        for p in range(NUM_PLAYERS):
            if state.hole_cards[p]:
                c1, c2 = sorted(state.hole_cards[p])
                idx = hand_index(c1, c2)
                ranges[p, idx] = 1.0
            else:
                ranges[p] = _uniform_range(board)
        history_str = str([(pl, str(a)) for pl, a in state.action_history])
        return cls(
            ranges=ranges,
            board=board,
            pot=state.pot,
            stacks=state.stacks.copy(),
            bets=state.bets.copy(),
            street=state.street,
            folded=state.folded.copy(),
            action_history_str=history_str,
        )

    # ------------------------------------------------------------------
    # Bayesian update
    # ------------------------------------------------------------------

    def update_range(self, player: int, action_likelihood: np.ndarray) -> None:
        """Multiply player *player*'s range by *action_likelihood* (Bayes' rule).

        Args:
            player: Player index whose range to update.
            action_likelihood: Array of shape (NUM_HANDS,) with the likelihood
                of observing the action for each possible hand.
        """
        self.ranges[player] *= action_likelihood
        total = self.ranges[player].sum()
        if total > 1e-12:
            self.ranges[player] /= total
        else:
            # Degenerate: reset to uniform to avoid NaN propagation
            self.ranges[player] = _uniform_range(self.board)

    # ------------------------------------------------------------------
    # Sampling
    # ------------------------------------------------------------------

    def sample_hand_profile(self) -> List[int]:
        """Sample a consistent hand profile (one hand per active player).

        Samples hands without replacement for active (non-folded) players,
        using each player's range as the sampling distribution.

        Returns:
            List of length NUM_PLAYERS where element *p* is the hand index
            of the sampled hand for player *p*, or -1 if folded.
        """
        dealt: set = set(self.board)
        profile: List[int] = []
        for p in range(NUM_PLAYERS):
            if self.folded[p]:
                profile.append(-1)
                continue
            # Remove hands blocked by already-dealt cards
            weights = self.ranges[p].copy()
            for idx in range(NUM_HANDS):
                c1, c2 = index_to_hand(idx)
                if c1 in dealt or c2 in dealt:
                    weights[idx] = 0.0
            total = weights.sum()
            if total < 1e-12:
                # Fallback: re-weight ignoring only hole-card conflicts
                weights = _uniform_range(list(dealt))
                total = weights.sum()
            weights /= total
            hand_idx = int(np.random.choice(NUM_HANDS, p=weights))
            c1, c2 = index_to_hand(hand_idx)
            dealt.add(c1)
            dealt.add(c2)
            profile.append(hand_idx)
        return profile

    # ------------------------------------------------------------------
    # Encoding (for neural network input)
    # ------------------------------------------------------------------

    def encode(self) -> np.ndarray:
        """Return a flat numpy vector encoding of the PBS.

        Encoding layout:
          [0 : NUM_PLAYERS * NUM_HANDS]  – flattened range arrays
          [NUM_PLAYERS * NUM_HANDS      : NUM_PLAYERS * NUM_HANDS + 52]  – board one-hot
          [... + 52 : ... + 52 + 4]     – street one-hot
          [... + 4  : ... + 4 + NUM_PLAYERS]  – pot / stacks / bets (normalised)
          [... + 4 + NUM_PLAYERS : ... + 4 + 3*NUM_PLAYERS]  – stacks, bets

        Total length: NUM_PLAYERS * NUM_HANDS + 52 + 4 + 3*NUM_PLAYERS
        """
        parts: List[np.ndarray] = []

        # Range distributions
        parts.append(self.ranges.flatten())

        # Board one-hot (52 dimensions)
        board_oh = np.zeros(NUM_CARDS, dtype=float)
        for c in self.board:
            board_oh[c] = 1.0
        parts.append(board_oh)

        # Street one-hot (4 dimensions)
        street_oh = np.zeros(4, dtype=float)
        street_oh[int(self.street)] = 1.0
        parts.append(street_oh)

        # Pot, stacks, bets (normalised by big blind = 1)
        norm = 100.0  # normalise by typical starting stack
        parts.append(np.array([self.pot / norm]))
        parts.append(self.stacks / norm)
        parts.append(self.bets / norm)

        return np.concatenate(parts, dtype=float)

    @staticmethod
    def encoding_size() -> int:
        """Return the dimension of the encoded PBS vector."""
        return NUM_PLAYERS * NUM_HANDS + NUM_CARDS + 4 + 1 + 2 * NUM_PLAYERS

    # ------------------------------------------------------------------
    # Utilities
    # ------------------------------------------------------------------

    def active_players(self) -> List[int]:
        """Return indices of non-folded players."""
        return [p for p in range(NUM_PLAYERS) if not self.folded[p]]

    def copy(self) -> "PublicBeliefState":
        return PublicBeliefState(
            ranges=self.ranges,
            board=self.board,
            pot=self.pot,
            stacks=self.stacks,
            bets=self.bets,
            street=self.street,
            folded=self.folded,
            action_history_str=self.action_history_str,
        )

    def __repr__(self) -> str:
        return (
            f"PublicBeliefState(street={self.street.name}, "
            f"board={self.board}, pot={self.pot:.2f}, "
            f"active={self.active_players()})"
        )
